print ("Tugas Python")
print ()
nama = input ("Masukan Nama Anda :")
pgln = input ("Masukan Panggilan :")
nim = input ("Masukan NIM :")
tmlhr = input ("Masukan Tempat Lahir :")
umur = input ("Masukan Umur Anda :")
tlpn = input ("Masukan Telepon :")
almt = input ("Masukan Alamat :")
print ()
print ("Assalamualaikum")
print ()
print ("Let me intruduce my self. My name is",nama,"but you can call me",pgln,"My NIM is",nim,"I was born in",tmlhr,"and i am",umur,"years old. I am very glad if you want to invite my house in",almt,". So, don't forget to call me before with the number",tlpn)
print()
print ("Thank You")
